sudo: false
language: node_js

addons:
  chrome: stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "cat /etc/init.d/xvfb"

node_js:
  - 6.10.3

script: lerna run build && lerna run test:ci
